/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    accommodations: Accommodation;
    entities: Entity;
    pages: Page;
    articles: Article;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    entities: EntitiesSelect<false> | EntitiesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en' | 'es') | ('fr' | 'en' | 'es')[];
  globals: {
    'site-config': SiteConfig;
    header: Header;
    footer: Footer;
    banner: Banner;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
  };
  locale: 'fr' | 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes, vídeos y documentos del site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen para quien no puede verla. Obligatorio.
   */
  alt: string;
  /**
   * Pie de foto opcional, visible junto a la imagen.
   */
  caption?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Se genera desde el nombre. Edítalo solo si necesitas otra URL.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * De menor a mayor. Controla el orden en los listados.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  name: string;
  /**
   * Se genera desde el nombre. Edítalo solo si necesitas otra URL.
   */
  slug?: string | null;
  type: 'emplacement' | 'mobilhome' | 'cottage' | 'chalet' | 'tente';
  /**
   * Ej: "Cyclo Rando", "Premium".
   */
  subtype?: string | null;
  /**
   * Resumen para las tarjetas de listado.
   */
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  specs: {
    /**
     * Personas.
     */
    capacity: number;
    bedrooms: number;
    /**
     * En m².
     */
    surface: number;
    hasAC?: boolean | null;
    petFriendly?: boolean | null;
  };
  bedroomDetails?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  equipment?:
    | {
        label: string;
        icon?:
          | (
              | 'utensils'
              | 'bed'
              | 'waves'
              | 'mapPin'
              | 'wifi'
              | 'car'
              | 'users'
              | 'calendar'
              | 'phone'
              | 'mail'
              | 'check'
              | 'x'
              | 'chevronRight'
              | 'chevronLeft'
              | 'chevronDown'
              | 'arrowRight'
              | 'star'
              | 'heart'
              | 'menu'
              | 'search'
              | 'pawPrint'
              | 'help'
              | 'video'
              | 'user'
              | 'train'
              | 'plane'
              | 'treePine'
              | 'leaf'
              | 'flame'
              | 'bike'
              | 'shoppingBag'
              | 'refreshCcw'
              | 'clock'
              | 'accessibility'
              | 'maximize2'
              | 'wind'
              | 'doorOpen'
              | 'coffee'
              | 'bath'
              | 'tv'
              | 'dog'
              | 'fileText'
              | 'download'
            )
          | null;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    /**
     * Precio "desde". Opcional.
     */
    from?: number | null;
    currency?: string | null;
    /**
     * Ej: "par nuit", "par semaine".
     */
    priceNote?: string | null;
  };
  media: {
    mainImage: number | Media;
    gallery?: (number | Media)[] | null;
    floorPlan?: (number | null) | Media;
    /**
     * URL del vídeo. Opcional.
     */
    video?: string | null;
  };
  documents?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        icon?:
          | (
              | 'utensils'
              | 'bed'
              | 'waves'
              | 'mapPin'
              | 'wifi'
              | 'car'
              | 'users'
              | 'calendar'
              | 'phone'
              | 'mail'
              | 'check'
              | 'x'
              | 'chevronRight'
              | 'chevronLeft'
              | 'chevronDown'
              | 'arrowRight'
              | 'star'
              | 'heart'
              | 'menu'
              | 'search'
              | 'pawPrint'
              | 'help'
              | 'video'
              | 'user'
              | 'train'
              | 'plane'
              | 'treePine'
              | 'leaf'
              | 'flame'
              | 'bike'
              | 'shoppingBag'
              | 'refreshCcw'
              | 'clock'
              | 'accessibility'
              | 'maximize2'
              | 'wind'
              | 'doorOpen'
              | 'coffee'
              | 'bath'
              | 'tv'
              | 'dog'
              | 'fileText'
              | 'download'
            )
          | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Si lo dejas vacío, el site propone otros de la misma categoría.
   */
  comparison?: (number | Accommodation)[] | null;
  category: number | Category;
  featured?: boolean | null;
  order?: number | null;
  booking?: {
    /**
     * ID del alojamiento en el motor de reservas.
     */
    externalId?: string | null;
    bookable?: boolean | null;
  };
  /**
   * Personalización por segmento. Se activa en el Hito 3 — déjalo vacío.
   */
  personalization?:
    | {
        segment: string;
        image: number | Media;
        gallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Secciones de la página, en el orden en que se pintan.
   */
  blocks?:
    | (
        | {
            title?: string | null;
            subtitle?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Qué se pinta en la columna del medio.
             */
            media: 'image' | 'embed' | 'carousel';
            image?: (number | null) | Media;
            images?: (number | Media)[] | null;
            /**
             * URL del contenido incrustado — por ejemplo, un mapa. Dominios admitidos: www.google.com, maps.google.com, www.youtube-nocookie.com, player.vimeo.com.
             */
            embedUrl?: string | null;
            /**
             * Columnas que ocupa el medio sobre doce. 6 es mitad y mitad; el diseño de referencia usa 5, 6 y 7.
             */
            split?: number | null;
            /**
             * Pone el medio a la derecha en lugar de a la izquierda.
             */
            reverse?: boolean | null;
            /**
             * Línea corta de acento a la izquierda del antetítulo.
             */
            eyebrowRule?: boolean | null;
            /**
             * Alineación vertical de las dos columnas.
             */
            align?: ('start' | 'center') | null;
            /**
             * Proporción del marco del medio.
             */
            ratio?: ('portrait' | 'landscape' | 'square') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Segunda línea del titular, en color de acento. Vacío deja el titular en una línea.
             */
            titleAccent?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Identificador para que el site inserte contenido propio en esta instancia (slot-registry.tsx). Déjalo vacío si no hay ninguno.
             */
            slotId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media-text';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Cuántos caben en una fila en pantalla grande. El diseño de referencia usa 3, 5 y 6. El tamaño de los iconos y la rampa responsive se derivan de este número.
             */
            columns?: number | null;
            /**
             * Iconos sueltos sobre el fondo, cada uno en su tarjeta, o lista de equipamiento (filas compactas en dos columnas, con incluido / excluido; ignora las columnas).
             */
            variant?: ('bare' | 'card' | 'equipment') | null;
            /**
             * Párrafo de entrada entre el titular y la rejilla. Distinto del antetítulo, que va encima y es una línea corta.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            items: {
              icon?:
                | (
                    | 'utensils'
                    | 'bed'
                    | 'waves'
                    | 'mapPin'
                    | 'wifi'
                    | 'car'
                    | 'users'
                    | 'calendar'
                    | 'phone'
                    | 'mail'
                    | 'check'
                    | 'x'
                    | 'chevronRight'
                    | 'chevronLeft'
                    | 'chevronDown'
                    | 'arrowRight'
                    | 'star'
                    | 'heart'
                    | 'menu'
                    | 'search'
                    | 'pawPrint'
                    | 'help'
                    | 'video'
                    | 'user'
                    | 'train'
                    | 'plane'
                    | 'treePine'
                    | 'leaf'
                    | 'flame'
                    | 'bike'
                    | 'shoppingBag'
                    | 'refreshCcw'
                    | 'clock'
                    | 'accessibility'
                    | 'maximize2'
                    | 'wind'
                    | 'doorOpen'
                    | 'coffee'
                    | 'bath'
                    | 'tv'
                    | 'dog'
                    | 'fileText'
                    | 'download'
                  )
                | null;
              label: string;
              description?: string | null;
              /**
               * Desmárcalo para pintarlo como no incluido (atenuado y con una X).
               */
              included?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'icon-grid';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Párrafo de entrada entre el titular y la rejilla.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Texto sobre la imagen, o imagen arriba y texto debajo.
             */
            card: 'overlay' | 'stacked';
            /**
             * Escala de la tarjeta con texto sobre la imagen.
             */
            cardSize?: ('default' | 'compact') | null;
            /**
             * Cuántas tarjetas caben en una fila. El diseño usa 3 y 4.
             */
            columns?: number | null;
            /**
             * Reparto asimétrico en columnas de doce, una por tarjeta y en ciclo. Vacío deja la rejilla uniforme. El diseño usa 5 y 7 en «Nos Hébergements».
             */
            spans?: number[] | null;
            /**
             * De dónde salen las tarjetas. Hoy solo se pintan las manuales; la resolución de colecciones llega con el resolver del site.
             */
            source?: ('manual' | 'accommodations' | 'entities' | 'articles') | null;
            sourceConfig?: {
              category?: string | null;
              limit?: number | null;
              featured?: boolean | null;
            };
            items?:
              | {
                  image: number | Media;
                  title: string;
                  subtitle?: string | null;
                  tag?: string | null;
                  url?: string | null;
                  date?: string | null;
                  readMoreLabel?: string | null;
                  /**
                   * Botón relleno o enlace suelto, como en el diseño.
                   */
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  id?: string | null;
                }[]
              | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Párrafo de entrada entre el titular y las tarjetas.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Qué artículos se muestran.
             */
            source: 'latest' | 'featured' | 'byCategory';
            category?: string | null;
            /**
             * Cuántos artículos se piden.
             */
            limit?: number | null;
            /**
             * Añade el resumen del artículo bajo el titular de cada tarjeta.
             */
            showExcerpt?: boolean | null;
            showMoreLink?: boolean | null;
            showMoreUrl?: string | null;
            showMoreLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
        | {
            title?: string | null;
            /**
             * Párrafo de entrada entre el titular y la galería.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * slider y slider-thumbs usan el carrusel; grid, masonry y collage son CSS puro.
             */
            variant?: ('slider' | 'slider-thumbs' | 'grid' | 'masonry' | 'collage') | null;
            images: {
              image: number | Media;
              /**
               * Obligatorio. Gana sobre el alt del archivo — describe la foto en el contexto de esta galería.
               */
              alt: string;
              caption?: string | null;
              id?: string | null;
            }[];
            /**
             * Columnas de la rejilla. Solo grid y masonry.
             */
            columns?: number | null;
            /**
             * Proporción del marco de cada imagen. auto respeta las dimensiones originales — es lo que hace masonry siempre, tenga o no este valor.
             */
            aspectRatio?: ('16/9' | '4/3' | '3/2' | '1/1' | 'auto') | null;
            /**
             * Abre un visor a pantalla completa al hacer click en una imagen.
             */
            lightbox?: boolean | null;
            /**
             * Avance automático. Solo slider y slider-thumbs.
             */
            autoplay?: boolean | null;
            /**
             * Milisegundos entre avances automáticos.
             */
            autoplayDelay?: number | null;
            /**
             * Vuelve al principio al llegar al final. Solo slider y slider-thumbs.
             */
            loop?: boolean | null;
            /**
             * Puntos de paginación bajo el carrusel. Solo slider.
             */
            showDots?: boolean | null;
            /**
             * Flechas de navegación. Solo slider y slider-thumbs.
             */
            showArrows?: boolean | null;
            /**
             * Transición entre slides. Solo slider.
             */
            effect?: ('slide' | 'fade') | null;
            /**
             * Cuántas slides se ven a la vez. Solo slider, para el multi-slide.
             */
            slidesPerView?: number | null;
            /**
             * Nivel del titular en la jerarquía de la página. Nunca h1.
             */
            headingLevel?: ('2' | '3' | '4') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Nombre y dirección junto al mapa. Se editan en Configuración del site → Contacto.
             */
            showAddress?: boolean | null;
            /**
             * Accesos (coche, tren, avión). Se editan en Configuración del site → Ubicación.
             */
            showTransport?: boolean | null;
            /**
             * Botones tras el de itinerario. Ej: «Plan du camping».
             */
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'map';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            links: {
              label: string;
              url: string;
              variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
              /**
               * Icono a la derecha del texto. Opcional.
               */
              icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            widgetTitle?: string | null;
            /**
             * manual usa el tipo de alojamiento de abajo. fromAccommodation lo deriva del alojamiento de la ficha — solo tiene efecto dentro de una ficha de alojamiento.
             */
            source?: ('manual' | 'fromAccommodation') | null;
            /**
             * Tipo de alojamiento a buscar. Solo aplica con source manual.
             */
            accommodationType?: ('all' | 'emplacement' | 'locatif') | null;
            /**
             * Activa el modo debug del widget del motor de reservas.
             */
            debug?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-search';
          }
        | {
            widgetTitle?: string | null;
            /**
             * Cuántos alojamientos carga el widget en total.
             */
            quantity?: number | null;
            /**
             * Cuántos se ven a la vez.
             */
            quantityToShow?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-favorites';
          }
        | {
            widgetTitle?: string | null;
            /**
             * manual usa las categorías de abajo. fromAccommodation usa el externalId del alojamiento de la ficha — solo tiene efecto dentro de una ficha de alojamiento.
             */
            source?: ('manual' | 'fromAccommodation') | null;
            /**
             * IDs de categoría del motor de reservas. En THR, consultar el panel de administración de THR para obtener los IDs.
             */
            categories?: string[] | null;
            /**
             * Muestra la foto del alojamiento en el widget.
             */
            showPicture?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-simple';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities".
 */
export interface Entity {
  id: number;
  type: 'service' | 'activity' | 'restaurant' | 'environment' | 'event' | 'custom';
  name: string;
  /**
   * Se genera desde el nombre. Edítalo solo si necesitas otra URL.
   */
  slug?: string | null;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  icon:
    | 'utensils'
    | 'bed'
    | 'waves'
    | 'mapPin'
    | 'wifi'
    | 'car'
    | 'users'
    | 'calendar'
    | 'phone'
    | 'mail'
    | 'check'
    | 'x'
    | 'chevronRight'
    | 'chevronLeft'
    | 'chevronDown'
    | 'arrowRight'
    | 'star'
    | 'heart'
    | 'menu'
    | 'search'
    | 'pawPrint'
    | 'help'
    | 'video'
    | 'user'
    | 'train'
    | 'plane'
    | 'treePine'
    | 'leaf'
    | 'flame'
    | 'bike'
    | 'shoppingBag'
    | 'refreshCcw'
    | 'clock'
    | 'accessibility'
    | 'maximize2'
    | 'wind'
    | 'doorOpen'
    | 'coffee'
    | 'bath'
    | 'tv'
    | 'dog'
    | 'fileText'
    | 'download';
  image: number | Media;
  gallery?: (number | Media)[] | null;
  /**
   * Etiqueta corta. Ej: "Village & port", "Sur place".
   */
  tag?: string | null;
  featured?: boolean | null;
  order?: number | null;
  schedule?: {
    periods?:
      | {
          label: string;
          icon: 'utensils' | 'wine' | 'clock';
          hours: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
  };
  features?:
    | {
        icon:
          | 'utensils'
          | 'bed'
          | 'waves'
          | 'mapPin'
          | 'wifi'
          | 'car'
          | 'users'
          | 'calendar'
          | 'phone'
          | 'mail'
          | 'check'
          | 'x'
          | 'chevronRight'
          | 'chevronLeft'
          | 'chevronDown'
          | 'arrowRight'
          | 'star'
          | 'heart'
          | 'menu'
          | 'search'
          | 'pawPrint'
          | 'help'
          | 'video'
          | 'user'
          | 'train'
          | 'plane'
          | 'treePine'
          | 'leaf'
          | 'flame'
          | 'bike'
          | 'shoppingBag'
          | 'refreshCcw'
          | 'clock'
          | 'accessibility'
          | 'maximize2'
          | 'wind'
          | 'doorOpen'
          | 'coffee'
          | 'bath'
          | 'tv'
          | 'dog'
          | 'fileText'
          | 'download';
        label: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        label: string;
        url: string;
        variant: 'primary' | 'outline';
        id?: string | null;
      }[]
    | null;
  /**
   * Si está activo, la entidad tiene URL propia.
   */
  hasOwnPage?: boolean | null;
  category?: (number | null) | Category;
  /**
   * Personalización por segmento. Se activa en el Hito 3 — déjalo vacío.
   */
  personalization?:
    | {
        segment: string;
        image: number | Media;
        gallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Se genera desde el título. Edítalo solo si necesitas otra URL.
   */
  slug?: string | null;
  type: 'home' | 'landing' | 'static' | 'listing' | 'contact' | 'faq';
  /**
   * Página de la que cuelga esta, para los breadcrumbs.
   */
  parent?: (number | null) | Page;
  hero: {
    variant: 'video' | 'image' | 'minimal' | 'none';
    media?: (number | null) | Media;
    /**
     * Línea corta sobre el titular. En el diseño, la localización.
     */
    eyebrow?: string | null;
    /**
     * Sustituye al título de la página en el hero.
     */
    title?: string | null;
    subtitle?: string | null;
    /**
     * Con "logo" el logo del site hace de titular. El h1 se pinta igual, oculto, para no dejar la página sin encabezado.
     */
    titleMode?: ('text' | 'logo') | null;
    align?: ('left' | 'center') | null;
    showBreadcrumbs?: boolean | null;
  };
  /**
   * Secciones de la página, en el orden en que se pintan.
   */
  blocks?:
    | (
        | {
            title?: string | null;
            subtitle?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Qué se pinta en la columna del medio.
             */
            media: 'image' | 'embed' | 'carousel';
            image?: (number | null) | Media;
            images?: (number | Media)[] | null;
            /**
             * URL del contenido incrustado — por ejemplo, un mapa. Dominios admitidos: www.google.com, maps.google.com, www.youtube-nocookie.com, player.vimeo.com.
             */
            embedUrl?: string | null;
            /**
             * Columnas que ocupa el medio sobre doce. 6 es mitad y mitad; el diseño de referencia usa 5, 6 y 7.
             */
            split?: number | null;
            /**
             * Pone el medio a la derecha en lugar de a la izquierda.
             */
            reverse?: boolean | null;
            /**
             * Línea corta de acento a la izquierda del antetítulo.
             */
            eyebrowRule?: boolean | null;
            /**
             * Alineación vertical de las dos columnas.
             */
            align?: ('start' | 'center') | null;
            /**
             * Proporción del marco del medio.
             */
            ratio?: ('portrait' | 'landscape' | 'square') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Segunda línea del titular, en color de acento. Vacío deja el titular en una línea.
             */
            titleAccent?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Identificador para que el site inserte contenido propio en esta instancia (slot-registry.tsx). Déjalo vacío si no hay ninguno.
             */
            slotId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media-text';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Cuántos caben en una fila en pantalla grande. El diseño de referencia usa 3, 5 y 6. El tamaño de los iconos y la rampa responsive se derivan de este número.
             */
            columns?: number | null;
            /**
             * Iconos sueltos sobre el fondo, cada uno en su tarjeta, o lista de equipamiento (filas compactas en dos columnas, con incluido / excluido; ignora las columnas).
             */
            variant?: ('bare' | 'card' | 'equipment') | null;
            /**
             * Párrafo de entrada entre el titular y la rejilla. Distinto del antetítulo, que va encima y es una línea corta.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            items: {
              icon?:
                | (
                    | 'utensils'
                    | 'bed'
                    | 'waves'
                    | 'mapPin'
                    | 'wifi'
                    | 'car'
                    | 'users'
                    | 'calendar'
                    | 'phone'
                    | 'mail'
                    | 'check'
                    | 'x'
                    | 'chevronRight'
                    | 'chevronLeft'
                    | 'chevronDown'
                    | 'arrowRight'
                    | 'star'
                    | 'heart'
                    | 'menu'
                    | 'search'
                    | 'pawPrint'
                    | 'help'
                    | 'video'
                    | 'user'
                    | 'train'
                    | 'plane'
                    | 'treePine'
                    | 'leaf'
                    | 'flame'
                    | 'bike'
                    | 'shoppingBag'
                    | 'refreshCcw'
                    | 'clock'
                    | 'accessibility'
                    | 'maximize2'
                    | 'wind'
                    | 'doorOpen'
                    | 'coffee'
                    | 'bath'
                    | 'tv'
                    | 'dog'
                    | 'fileText'
                    | 'download'
                  )
                | null;
              label: string;
              description?: string | null;
              /**
               * Desmárcalo para pintarlo como no incluido (atenuado y con una X).
               */
              included?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'icon-grid';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Párrafo de entrada entre el titular y la rejilla.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Texto sobre la imagen, o imagen arriba y texto debajo.
             */
            card: 'overlay' | 'stacked';
            /**
             * Escala de la tarjeta con texto sobre la imagen.
             */
            cardSize?: ('default' | 'compact') | null;
            /**
             * Cuántas tarjetas caben en una fila. El diseño usa 3 y 4.
             */
            columns?: number | null;
            /**
             * Reparto asimétrico en columnas de doce, una por tarjeta y en ciclo. Vacío deja la rejilla uniforme. El diseño usa 5 y 7 en «Nos Hébergements».
             */
            spans?: number[] | null;
            /**
             * De dónde salen las tarjetas. Hoy solo se pintan las manuales; la resolución de colecciones llega con el resolver del site.
             */
            source?: ('manual' | 'accommodations' | 'entities' | 'articles') | null;
            sourceConfig?: {
              category?: string | null;
              limit?: number | null;
              featured?: boolean | null;
            };
            items?:
              | {
                  image: number | Media;
                  title: string;
                  subtitle?: string | null;
                  tag?: string | null;
                  url?: string | null;
                  date?: string | null;
                  readMoreLabel?: string | null;
                  /**
                   * Botón relleno o enlace suelto, como en el diseño.
                   */
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  id?: string | null;
                }[]
              | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Párrafo de entrada entre el titular y las tarjetas.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Qué artículos se muestran.
             */
            source: 'latest' | 'featured' | 'byCategory';
            category?: string | null;
            /**
             * Cuántos artículos se piden.
             */
            limit?: number | null;
            /**
             * Añade el resumen del artículo bajo el titular de cada tarjeta.
             */
            showExcerpt?: boolean | null;
            showMoreLink?: boolean | null;
            showMoreUrl?: string | null;
            showMoreLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
        | {
            title?: string | null;
            /**
             * Párrafo de entrada entre el titular y la galería.
             */
            description?: string | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * slider y slider-thumbs usan el carrusel; grid, masonry y collage son CSS puro.
             */
            variant?: ('slider' | 'slider-thumbs' | 'grid' | 'masonry' | 'collage') | null;
            images: {
              image: number | Media;
              /**
               * Obligatorio. Gana sobre el alt del archivo — describe la foto en el contexto de esta galería.
               */
              alt: string;
              caption?: string | null;
              id?: string | null;
            }[];
            /**
             * Columnas de la rejilla. Solo grid y masonry.
             */
            columns?: number | null;
            /**
             * Proporción del marco de cada imagen. auto respeta las dimensiones originales — es lo que hace masonry siempre, tenga o no este valor.
             */
            aspectRatio?: ('16/9' | '4/3' | '3/2' | '1/1' | 'auto') | null;
            /**
             * Abre un visor a pantalla completa al hacer click en una imagen.
             */
            lightbox?: boolean | null;
            /**
             * Avance automático. Solo slider y slider-thumbs.
             */
            autoplay?: boolean | null;
            /**
             * Milisegundos entre avances automáticos.
             */
            autoplayDelay?: number | null;
            /**
             * Vuelve al principio al llegar al final. Solo slider y slider-thumbs.
             */
            loop?: boolean | null;
            /**
             * Puntos de paginación bajo el carrusel. Solo slider.
             */
            showDots?: boolean | null;
            /**
             * Flechas de navegación. Solo slider y slider-thumbs.
             */
            showArrows?: boolean | null;
            /**
             * Transición entre slides. Solo slider.
             */
            effect?: ('slide' | 'fade') | null;
            /**
             * Cuántas slides se ven a la vez. Solo slider, para el multi-slide.
             */
            slidesPerView?: number | null;
            /**
             * Nivel del titular en la jerarquía de la página. Nunca h1.
             */
            headingLevel?: ('2' | '3' | '4') | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Titular en color de texto, o en color de marca para destacar.
             */
            headingTone?: ('default' | 'brand') | null;
            /**
             * Fondo de la sección. Las secciones suelen alternar.
             */
            background?: ('default' | 'muted' | 'none') | null;
            /**
             * Nombre y dirección junto al mapa. Se editan en Configuración del site → Contacto.
             */
            showAddress?: boolean | null;
            /**
             * Accesos (coche, tren, avión). Se editan en Configuración del site → Ubicación.
             */
            showTransport?: boolean | null;
            /**
             * Botones tras el de itinerario. Ej: «Plan du camping».
             */
            ctas?:
              | {
                  label: string;
                  url: string;
                  variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
                  /**
                   * Icono a la derecha del texto. Opcional.
                   */
                  icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'map';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            links: {
              label: string;
              url: string;
              variant?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'link-underline') | null;
              /**
               * Icono a la derecha del texto. Opcional.
               */
              icon?: ('arrowRight' | 'chevronRight' | 'calendar' | 'phone' | 'mail') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            widgetTitle?: string | null;
            /**
             * manual usa el tipo de alojamiento de abajo. fromAccommodation lo deriva del alojamiento de la ficha — solo tiene efecto dentro de una ficha de alojamiento.
             */
            source?: ('manual' | 'fromAccommodation') | null;
            /**
             * Tipo de alojamiento a buscar. Solo aplica con source manual.
             */
            accommodationType?: ('all' | 'emplacement' | 'locatif') | null;
            /**
             * Activa el modo debug del widget del motor de reservas.
             */
            debug?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-search';
          }
        | {
            widgetTitle?: string | null;
            /**
             * Cuántos alojamientos carga el widget en total.
             */
            quantity?: number | null;
            /**
             * Cuántos se ven a la vez.
             */
            quantityToShow?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-favorites';
          }
        | {
            widgetTitle?: string | null;
            /**
             * manual usa las categorías de abajo. fromAccommodation usa el externalId del alojamiento de la ficha — solo tiene efecto dentro de una ficha de alojamiento.
             */
            source?: ('manual' | 'fromAccommodation') | null;
            /**
             * IDs de categoría del motor de reservas. En THR, consultar el panel de administración de THR para obtener los IDs.
             */
            categories?: string[] | null;
            /**
             * Muestra la foto del alojamiento en el widget.
             */
            showPicture?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking-simple';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
    canonicalUrl?: string | null;
  };
  /**
   * Personalización por segmento. Se activa en el Hito 3 — déjalo vacío.
   */
  personalization?:
    | {
        segment: string;
        image: number | Media;
        gallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Se genera desde el título. Edítalo solo si necesitas otra URL.
   */
  slug?: string | null;
  /**
   * Resumen corto para las tarjetas del listado.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  category: string;
  publishedAt: string;
  author?: string | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes recibidos desde la página de contacto. Se conservan 90 días (RGPD): bórralos pasado ese plazo o cuando el visitante lo pida.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Cuándo aceptó la política de privacidad.
   */
  consentAt: string;
  /**
   * Hash de la IP con sal, para el límite de envíos. No es la IP.
   */
  ipHash: string;
  /**
   * Si el aviso por email llegó a salir.
   */
  emailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null)
    | ({
        relationTo: 'entities';
        value: number | Entity;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  subtype?: T;
  shortDescription?: T;
  description?: T;
  specs?:
    | T
    | {
        capacity?: T;
        bedrooms?: T;
        surface?: T;
        hasAC?: T;
        petFriendly?: T;
      };
  bedroomDetails?:
    | T
    | {
        description?: T;
        id?: T;
      };
  equipment?:
    | T
    | {
        label?: T;
        icon?: T;
        included?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        from?: T;
        currency?: T;
        priceNote?: T;
      };
  media?:
    | T
    | {
        mainImage?: T;
        gallery?: T;
        floorPlan?: T;
        video?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  comparison?: T;
  category?: T;
  featured?: T;
  order?: T;
  booking?:
    | T
    | {
        externalId?: T;
        bookable?: T;
      };
  personalization?:
    | T
    | {
        segment?: T;
        image?: T;
        gallery?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        'media-text'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              media?: T;
              image?: T;
              images?: T;
              embedUrl?: T;
              split?: T;
              reverse?: T;
              eyebrowRule?: T;
              align?: T;
              ratio?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              titleAccent?: T;
              background?: T;
              slotId?: T;
              id?: T;
              blockName?: T;
            };
        'icon-grid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              columns?: T;
              variant?: T;
              description?: T;
              background?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    description?: T;
                    included?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'card-grid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              description?: T;
              background?: T;
              card?: T;
              cardSize?: T;
              columns?: T;
              spans?: T;
              source?: T;
              sourceConfig?:
                | T
                | {
                    category?: T;
                    limit?: T;
                    featured?: T;
                  };
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    tag?: T;
                    url?: T;
                    date?: T;
                    readMoreLabel?: T;
                    variant?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              description?: T;
              background?: T;
              source?: T;
              category?: T;
              limit?: T;
              showExcerpt?: T;
              showMoreLink?: T;
              showMoreUrl?: T;
              showMoreLabel?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
              background?: T;
              variant?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              aspectRatio?: T;
              lightbox?: T;
              autoplay?: T;
              autoplayDelay?: T;
              loop?: T;
              showDots?: T;
              showArrows?: T;
              effect?: T;
              slidesPerView?: T;
              headingLevel?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              background?: T;
              showAddress?: T;
              showTransport?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'booking-search'?:
          | T
          | {
              widgetTitle?: T;
              source?: T;
              accommodationType?: T;
              debug?: T;
              id?: T;
              blockName?: T;
            };
        'booking-favorites'?:
          | T
          | {
              widgetTitle?: T;
              quantity?: T;
              quantityToShow?: T;
              id?: T;
              blockName?: T;
            };
        'booking-simple'?:
          | T
          | {
              widgetTitle?: T;
              source?: T;
              categories?: T;
              showPicture?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities_select".
 */
export interface EntitiesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  image?: T;
  gallery?: T;
  tag?: T;
  featured?: T;
  order?: T;
  schedule?:
    | T
    | {
        periods?:
          | T
          | {
              label?: T;
              icon?: T;
              hours?: T;
              id?: T;
            };
        note?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        label?: T;
        detail?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  hasOwnPage?: T;
  category?: T;
  personalization?:
    | T
    | {
        segment?: T;
        image?: T;
        gallery?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  parent?: T;
  hero?:
    | T
    | {
        variant?: T;
        media?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        titleMode?: T;
        align?: T;
        showBreadcrumbs?: T;
      };
  blocks?:
    | T
    | {
        'media-text'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              media?: T;
              image?: T;
              images?: T;
              embedUrl?: T;
              split?: T;
              reverse?: T;
              eyebrowRule?: T;
              align?: T;
              ratio?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              titleAccent?: T;
              background?: T;
              slotId?: T;
              id?: T;
              blockName?: T;
            };
        'icon-grid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              columns?: T;
              variant?: T;
              description?: T;
              background?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    description?: T;
                    included?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'card-grid'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              description?: T;
              background?: T;
              card?: T;
              cardSize?: T;
              columns?: T;
              spans?: T;
              source?: T;
              sourceConfig?:
                | T
                | {
                    category?: T;
                    limit?: T;
                    featured?: T;
                  };
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    tag?: T;
                    url?: T;
                    date?: T;
                    readMoreLabel?: T;
                    variant?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              description?: T;
              background?: T;
              source?: T;
              category?: T;
              limit?: T;
              showExcerpt?: T;
              showMoreLink?: T;
              showMoreUrl?: T;
              showMoreLabel?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
              background?: T;
              variant?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              aspectRatio?: T;
              lightbox?: T;
              autoplay?: T;
              autoplayDelay?: T;
              loop?: T;
              showDots?: T;
              showArrows?: T;
              effect?: T;
              slidesPerView?: T;
              headingLevel?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              title?: T;
              subtitle?: T;
              headingTone?: T;
              background?: T;
              showAddress?: T;
              showTransport?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'booking-search'?:
          | T
          | {
              widgetTitle?: T;
              source?: T;
              accommodationType?: T;
              debug?: T;
              id?: T;
              blockName?: T;
            };
        'booking-favorites'?:
          | T
          | {
              widgetTitle?: T;
              quantity?: T;
              quantityToShow?: T;
              id?: T;
              blockName?: T;
            };
        'booking-simple'?:
          | T
          | {
              widgetTitle?: T;
              source?: T;
              categories?: T;
              showPicture?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
        canonicalUrl?: T;
      };
  personalization?:
    | T
    | {
        segment?: T;
        image?: T;
        gallery?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  consentAt?: T;
  ipHash?: T;
  emailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * Todo site nace cerrado. Mientras esté en «Cerrado», todas las páginas salen con noindex, robots.txt lo bloquea todo y el sitemap queda vacío, diga lo que diga cada página. Cámbialo a «Abierto» solo cuando el cliente decida publicar.
   */
  indexing: 'noindex' | 'index';
  general: {
    siteName: string;
    siteDescription: string;
    logo: number | Media;
    /**
     * Versión para fondos oscuros.
     */
    logoInverted: number | Media;
    /**
     * Clasificación. Opcional.
     */
    stars?: number | null;
    openingDates: string;
    /**
     * Tipo de negocio. Decide el tipo del JSON-LD del negocio.
     */
    businessType: 'campground' | 'hotel' | 'resort' | 'guesthouse';
  };
  contact: {
    address: string;
    postalCode: string;
    city: string;
    country: string;
    phone: string;
    email: string;
  };
  location: {
    latitude: number;
    longitude: number;
    transport?:
      | {
          icon: 'car' | 'train' | 'plane';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  maps: {
    /**
     * Mapa interactivo que se carga tras aceptar las cookies.
     */
    provider: 'osm' | 'google';
    /**
     * Clave de la Embed API. Opcional. Es pública (va en el iframe): restríngela por dominio en Google Cloud.
     */
    googleMapsApiKey?: string | null;
    /**
     * Captura del mapa que se ve sin consentimiento. Sin ella, un panel neutro con el enlace a Google Maps.
     */
    staticImage?: (number | null) | Media;
    /**
     * Provisional hasta integrar el gestor de cookies: muestra siempre el mapa interactivo. Déjalo desactivado en producción.
     */
    forceConsent?: boolean | null;
  };
  contactForm: {
    /**
     * Opciones del desplegable «Sujet». Sin ninguna, el formulario no se muestra.
     */
    subjects?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Página de la política de privacidad, enlazada desde la casilla RGPD.
     */
    privacyPolicyUrl: string;
    /**
     * Quién recibe los mensajes. Vacío: el email de Contacto.
     */
    recipient?: string | null;
  };
  languages: {
    /**
     * Códigos de idioma: fr, en, es.
     */
    available: string[];
    default: string;
    /**
     * Si el idioma principal lleva prefijo en la URL.
     */
    prefixDefault: boolean;
    /**
     * El Hito 1 solo implementa "prefix".
     */
    strategy: 'prefix' | 'domain';
    domainMap?:
      | {
          locale: string;
          domain: string;
          id?: string | null;
        }[]
      | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
    /**
     * Ej: @mi_camping
     */
    instagramHandle?: string | null;
  };
  /**
   * Métodos de pago aceptados. Ej: CB, Visa, Mastercard.
   */
  payments?: string[] | null;
  legal?: {
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  tracking?: {
    gtmId?: string | null;
    gaId?: string | null;
    metaPixelId?: string | null;
  };
  customCode?:
    | {
        label: string;
        code: string;
        position: 'head' | 'bodyStart' | 'bodyEnd';
        /**
         * Si solo debe cargarse tras aceptar cookies.
         */
        requiresConsent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  booking: {
    engine: 'thr' | 'mastercamping' | 'witbooking' | 'resalys' | 'none';
    /**
     * Código del camping en THR. Ej: MICAMPING.
     */
    codeCamping?: string | null;
    /**
     * ID del site en THR. Opcional — solo si el camping tiene varios sites.
     */
    siteId?: string | null;
    /**
     * Widgets THR adicionales.
     */
    features?: {
      /**
       * Activar bloque de favoritos.
       */
      favorites?: boolean | null;
      /**
       * Activar bloque de disponibilidad rápida.
       */
      simpleblock?: boolean | null;
    };
    /**
     * ID numérico de la propiedad en Mastercamping. Ej: 3.
     */
    idProperty?: number | null;
    /**
     * URL del sistema de reservas. Ej: https://booking.example.com
     */
    bookingUrl?: string | null;
    /**
     * Disposición del formulario de búsqueda.
     */
    layout?: ('horizontal' | 'vertical') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  topBar: {
    links?:
      | {
          label: string;
          icon: 'help' | 'phone' | 'mail' | 'video' | 'user' | 'custom';
          url: string;
          id?: string | null;
        }[]
      | null;
    showLogin?: boolean | null;
    bookingButtonLabel: string;
  };
  navigation?:
    | {
        label: string;
        url: string;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  virtualAssistant?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    placeholder?: string | null;
  };
  columns?:
    | {
        title: string;
        type: 'links' | 'text' | 'schedule' | 'newsletter';
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        newsletter?: {
          description?: string | null;
          buttonLabel: string;
          provider: 'mailchimp' | 'sendinblue' | 'custom';
          actionUrl: string;
        };
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        name: string;
        logo: number | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: number;
  enabled?: boolean | null;
  message: string;
  type: 'info' | 'warning' | 'promo';
  dismissible?: boolean | null;
  /**
   * Destino al pulsar el aviso.
   */
  url?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  indexing?: T;
  general?:
    | T
    | {
        siteName?: T;
        siteDescription?: T;
        logo?: T;
        logoInverted?: T;
        stars?: T;
        openingDates?: T;
        businessType?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        postalCode?: T;
        city?: T;
        country?: T;
        phone?: T;
        email?: T;
      };
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        transport?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  maps?:
    | T
    | {
        provider?: T;
        googleMapsApiKey?: T;
        staticImage?: T;
        forceConsent?: T;
      };
  contactForm?:
    | T
    | {
        subjects?:
          | T
          | {
              label?: T;
              id?: T;
            };
        privacyPolicyUrl?: T;
        recipient?: T;
      };
  languages?:
    | T
    | {
        available?: T;
        default?: T;
        prefixDefault?: T;
        strategy?: T;
        domainMap?:
          | T
          | {
              locale?: T;
              domain?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
        linkedin?: T;
        tiktok?: T;
        instagramHandle?: T;
      };
  payments?: T;
  legal?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  tracking?:
    | T
    | {
        gtmId?: T;
        gaId?: T;
        metaPixelId?: T;
      };
  customCode?:
    | T
    | {
        label?: T;
        code?: T;
        position?: T;
        requiresConsent?: T;
        id?: T;
      };
  booking?:
    | T
    | {
        engine?: T;
        codeCamping?: T;
        siteId?: T;
        features?:
          | T
          | {
              favorites?: T;
              simpleblock?: T;
            };
        idProperty?: T;
        bookingUrl?: T;
        layout?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              icon?: T;
              url?: T;
              id?: T;
            };
        showLogin?: T;
        bookingButtonLabel?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  virtualAssistant?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        placeholder?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        type?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        content?: T;
        newsletter?:
          | T
          | {
              description?: T;
              buttonLabel?: T;
              provider?: T;
              actionUrl?: T;
            };
        id?: T;
      };
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  enabled?: T;
  message?: T;
  type?: T;
  dismissible?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}